import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { blogPosts } from '../src/data/posts/index';
import type { BlogPostSummary } from '../src/types/blog-summary';

const summaries: BlogPostSummary[] = blogPosts.map((p) => ({
  slug: p.slug,
  title: p.title,
  date: p.date,
  ...(p.updated && { updated: p.updated }),
  excerpt: p.excerpt,
  readingTime: p.readingTime,
  keywords: p.keywords,
  ...(p.relatedProject && { relatedProject: p.relatedProject }),
}));

const out = `// Auto-generated by scripts/generate-blog-summaries.ts. Do not edit.
import type { BlogPostSummary } from '@/types/blog-summary';

export const blogSummaries: BlogPostSummary[] = ${JSON.stringify(summaries, null, 2)};
`;

const target = resolve(process.cwd(), 'src/data/blog-summaries.generated.ts');
writeFileSync(target, out);
console.log(`[blog-summaries] wrote ${summaries.length} summaries -> ${target}`);
